version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  reviewers:
  - omjadas
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  reviewers:
  - omjadas
