name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14.x
      - name: npm ci
        run: npm ci
